#Continiues Docker image deploiment of APERIMs EpitopeSelector
sudo: required

services:
  - docker

language: python

install:
  - docker build -t aperim/immunonodes .
  
script:
  docker run aperim/immunonodes  epitopeprediction.py -h

